language: ruby
rvm:
  - 2.2.2
  - 2.1.5
  - 2.0.0
  - rbx-2
env:
  - DB=sqlite

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile

before_install: gem install bundler
